name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install rails
          bundle install

      - name: Scan for common Rails security vulnerabilities
        run: bundle exec brakeman --no-pager

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install rails
          bundle install

      - name: Lint code for consistent style
        run: bundle exec rubocop

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y libpq-dev libvips

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install project dependencies
        run: |
          gem install rails
          bundle config set --local without 'development'
          bundle install --jobs 4 --retry 3

      - name: Print environment info
        run: |
          echo "Ruby version:"
          ruby -v
          echo "Rails version:"
          bundle exec rails -v
          echo "Gem list:"
          gem list
          echo "Bundle list:"
          bundle list

      - name: Debug Zeitwerk autoloading
        run: |
          echo "Content of api_controller.rb:"
          cat app/controllers/api/v1/api_controller.rb || echo "File not found"
          echo "List of files in app/controllers/api/v1:"
          ls -R app/controllers/api/v1 || echo "Directory not found"

      - name: Setup test database
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_database
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load

      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_database
        run: bundle exec rails test